function...
    [GRIPPER_Z_PICK_UP_CUBE_FACING_DOWN, GRIPPER_Z_ABOVE_CUBE_PICK_UP_FACING_DOWN,...
    GRIPPER_Z_PICK_UP_CUBE_FACING_STRAIGHT, GRIPPER_Z_ABOVE_CUBE_PICK_UP_FACING_STRAIGHT]...
    = getTask2GripperZValues()
%GETTASK2GRIPPERZVALUES
    
    % Cube specific values
    % Cube has sidelength of 2.5cm, cube stand's top edge is 19.8mm from
    % base-plate
    GRIPPER_Z_PICK_UP_CUBE_FACING_DOWN = 0.045;
    GRIPPER_Z_ABOVE_CUBE_PICK_UP_FACING_DOWN = 0.06;
    
    GRIPPER_Z_PICK_UP_CUBE_FACING_STRAIGHT = 0.0325;
    GRIPPER_Z_ABOVE_CUBE_PICK_UP_FACING_STRAIGHT = 0.0475;
end
