function waypoints = getTask4Waypoints(...
    gripperOpenPos, gripperPenCubeHoldPos...
)
%GETTASK4WAYPOINTS

    main_waypoints = load(".\config\waypoints_task4_without_writing.mat").waypoints;
    drawing_waypoints = getTask4DrawingWaypoints(...
        gripperOpenPos, gripperPenCubeHoldPos...
    );
    waypoints = [main_waypoints, drawing_waypoints];
end
