function waypoints = waypointsForMovingBetweenStartFinish(...
    startX, startY, endX, endY,...
    gripperZPickUpCubeFacingDown, gripperZAbovePickUpCubeFacingDown,...
    gripperZPlaceDownCubeFacingDown, gripperZAbovePlacedCubeFacingDown,...
    gripperZPickUpCubeFacingStraight, gripperZAbovePickUpCubeFacingStraight,...
    gripperZPlaceDownCubeFacingStraight, gripperZAbovePlacedCubeFacingStraight,...
    gripperOpenPos, gripperCubeHoldPos...
)
%WAYPOINTSFORMOVINGBETWEENSTARTFINISH First tries
%waypointsForMovingBetweenStartFinishFacingDown and uses
%waypointsForMovingBetweenStartFinishFacingStraight if this does not
%produce any valid IK solutions.

    waypoints = waypointsForMovingBetweenStartFinishFacingDown(...
                    startX, startY, endX, endY,...
                    gripperZPickUpCubeFacingDown, gripperZAbovePickUpCubeFacingDown,...
                    gripperZPlaceDownCubeFacingDown, gripperZAbovePlacedCubeFacingDown,...
                    gripperOpenPos, gripperCubeHoldPos...
                );
    if ~doValidIKExist(waypoints)
        fprintf("waypointsForMovingBetweenStartFinish: Failed with gripper " +...
            "facing down, trying with gripper facing straight\n");

        waypoints = waypointsForMovingBetweenStartFinishFacingStraight(...
                        startX, startY, endX, endY,...
                        gripperZPickUpCubeFacingStraight, gripperZAbovePickUpCubeFacingStraight,...
                        gripperZPlaceDownCubeFacingStraight, gripperZAbovePlacedCubeFacingStraight,...
                        gripperOpenPos, gripperCubeHoldPos...
                    );
    end
end
